import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./Shared/Navbar";
import { Footer } from "./Shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "IQQuest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <Navbar></Navbar>
        </nav>
        <div className="min-h-80">
        {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
